const countries = [
  { country: "Afghanistan", code: "AF", regex: "^\\d{4}$" },
  { country: "Albania", code: "AL", regex: "^\\d{4}$" },
  { country: "Algeria", code: "DZ", regex: "^\\d{5}$" },
  { country: "Andorra", code: "AD", regex: "^AD\\d{3}$" },
  { country: "Angola", code: "AO", regex: null },
  { country: "Antigua and Barbuda", code: "AG", regex: null },
  { country: "Argentina", code: "AR", regex: "^([A-Z]\\d{4}[A-Z]{3}|\\d{4})$" },
  { country: "Armenia", code: "AM", regex: "^\\d{4}$" },
  { country: "Australia", code: "AU", regex: "^\\d{4}$" },
  { country: "Austria", code: "AT", regex: "^\\d{4}$" },
  { country: "Azerbaijan", code: "AZ", regex: "^AZ\\d{4}$" },
  { country: "Bahamas", code: "BS", regex: null },
  { country: "Bahrain", code: "BH", regex: "^\\d{3,4}$" },
  { country: "Bangladesh", code: "BD", regex: "^\\d{4}$" },
  { country: "Barbados", code: "BB", regex: "^BB\\d{5}$" },
  { country: "Belarus", code: "BY", regex: "^\\d{6}$" },
  { country: "Belgium", code: "BE", regex: "^\\d{4}$" },
  { country: "Belize", code: "BZ", regex: null },
  { country: "Benin", code: "BJ", regex: null },
  { country: "Bhutan", code: "BT", regex: "^\\d{5}$" },
  { country: "Bolivia", code: "BO", regex: null },
  { country: "Bosnia and Herzegovina", code: "BA", regex: "^\\d{5}$" },
  { country: "Botswana", code: "BW", regex: null },
  { country: "Brazil", code: "BR", regex: "^\\d{5}-?\\d{3}$" },
  { country: "Brunei", code: "BN", regex: "^[A-Z]{2}\\d{4}$" },
  { country: "Bulgaria", code: "BG", regex: "^\\d{4}$" },
  { country: "Burkina Faso", code: "BF", regex: null },
  { country: "Burundi", code: "BI", regex: null },
  { country: "Cabo Verde", code: "CV", regex: "^\\d{4}$" },
  { country: "Cambodia", code: "KH", regex: "^\\d{6}$" },
  { country: "Cameroon", code: "CM", regex: null },
  { country: "Canada", code: "CA", regex: "^[A-CEGHJ-NPR-TVXY]\\d[A-CEGHJ-NPR-TV-Z] ?\\d[A-CEGHJ-NPR-TV-Z]\\d$" },
  { country: "Central African Republic", code: "CF", regex: null },
  { country: "Chad", code: "TD", regex: "^\\d{5}$" },
  { country: "Chile", code: "CL", regex: "^\\d{7}$" },
  { country: "China", code: "CN", regex: "^\\d{6}$" },
  { country: "Colombia", code: "CO", regex: "^\\d{6}$" },
  { country: "Comoros", code: "KM", regex: null },
  { country: "Congo (Brazzaville)", code: "CG", regex: null },
  { country: "Congo (Kinshasa)", code: "CD", regex: null },
  { country: "Costa Rica", code: "CR", regex: "^\\d{5}$" },
  { country: "Croatia", code: "HR", regex: "^\\d{5}$" },
  { country: "Cuba", code: "CU", regex: "^\\d{5}$" },
  { country: "Cyprus", code: "CY", regex: "^\\d{4}$" },
  { country: "Czech Republic", code: "CZ", regex: "^\\d{3} ?\\d{2}$" },
  { country: "Denmark", code: "DK", regex: "^\\d{4}$" },
  { country: "Djibouti", code: "DJ", regex: null },
  { country: "Dominica", code: "DM", regex: null },
  { country: "Dominican Republic", code: "DO", regex: "^\\d{5}$" },
  { country: "Ecuador", code: "EC", regex: "^\\d{6}$" },
  { country: "Egypt", code: "EG", regex: "^\\d{5}$" },
  { country: "El Salvador", code: "SV", regex: "^01101$" },
  { country: "Equatorial Guinea", code: "GQ", regex: null },
  { country: "Eritrea", code: "ER", regex: null },
  { country: "Estonia", code: "EE", regex: "^\\d{5}$" },
  { country: "Eswatini", code: "SZ", regex: "^[A-Z]\\d{3}$" },
  { country: "Ethiopia", code: "ET", regex: "^\\d{4}$" },
  { country: "Fiji", code: "FJ", regex: null },
  { country: "Finland", code: "FI", regex: "^\\d{5}$" },
  { country: "France", code: "FR", regex: "^\\d{5}$" },
  { country: "Gabon", code: "GA", regex: null },
  { country: "Gambia", code: "GM", regex: null },
  { country: "Georgia", code: "GE", regex: "^\\d{4}$" },
  { country: "Germany", code: "DE", regex: "^\\d{5}$" },
  { country: "Ghana", code: "GH", regex: "^[A-Z]{2}-?\\d{3,4}-?\\d{4}$" },
  { country: "Greece", code: "GR", regex: "^\\d{3} ?\\d{2}$" },
  { country: "Grenada", code: "GD", regex: null },
  { country: "Guatemala", code: "GT", regex: "^\\d{5}$" },
  { country: "Guinea", code: "GN", regex: "^\\d{3}$" },
  { country: "Guinea-Bissau", code: "GW", regex: "^\\d{4}$" },
  { country: "Guyana", code: "GY", regex: null },
  { country: "Haiti", code: "HT", regex: "^\\d{4}$" },
  { country: "Honduras", code: "HN", regex: "^\\d{5}$" },
  { country: "Hungary", code: "HU", regex: "^\\d{4}$" },
  { country: "Iceland", code: "IS", regex: "^\\d{3}$" },
  { country: "India", code: "IN", regex: "^[1-9]\\d{5}$" },
  { country: "Indonesia", code: "ID", regex: "^\\d{5}$" },
  { country: "Iran", code: "IR", regex: "^\\d{5}-?\\d{5}$" },
  { country: "Iraq", code: "IQ", regex: "^\\d{5}$" },
  { country: "Ireland", code: "IE", regex: "^[A-Z\\d]{3} ?[A-Z\\d]{4}$" },
  { country: "Israel", code: "IL", regex: "^\\d{7}$" },
  { country: "Italy", code: "IT", regex: "^\\d{5}$" },
  { country: "Jamaica", code: "JM", regex: null },
  { country: "Japan", code: "JP", regex: "^\\d{3}-?\\d{4}$" },
  { country: "Jordan", code: "JO", regex: "^\\d{5}$" },
  { country: "Kazakhstan", code: "KZ", regex: "^([A-Z\\d]{7}|\\d{6})$" },
  { country: "Kenya", code: "KE", regex: "^\\d{5}$" },
  { country: "Kiribati", code: "KI", regex: null },
  { country: "Kuwait", code: "KW", regex: "^\\d{5}$" },
  { country: "Kyrgyzstan", code: "KG", regex: "^\\d{6}$" },
  { country: "Laos", code: "LA", regex: "^\\d{5}$" },
  { country: "Latvia", code: "LV", regex: "^LV-\\d{4}$" },
  { country: "Lebanon", code: "LB", regex: "^(\\d{4}|\\d{8})$" },
  { country: "Lesotho", code: "LS", regex: "^\\d{3}$" },
  { country: "Liberia", code: "LR", regex: "^\\d{4}$" },
  { country: "Libya", code: "LY", regex: null },
  { country: "Liechtenstein", code: "LI", regex: "^\\d{4}$" },
  { country: "Lithuania", code: "LT", regex: "^LT-\\d{5}$" },
  { country: "Luxembourg", code: "LU", regex: "^\\d{4}$" },
  { country: "Madagascar", code: "MG", regex: "^\\d{3}$" },
  { country: "Malawi", code: "MW", regex: null },
  { country: "Malaysia", code: "MY", regex: "^\\d{5}$" },
  { country: "Maldives", code: "MV", regex: "^\\d{5}$" },
  { country: "Mali", code: "ML", regex: null },
  { country: "Malta", code: "MT", regex: "^[A-Z]{3} ?\\d{2,4}$" },
  { country: "Marshall Islands", code: "MH", regex: "^\\d{5}(-\\d{4})?$" },
  { country: "Mauritania", code: "MR", regex: null },
  { country: "Mauritius", code: "MU", regex: "^(\\d{5}|[A-Z\\d]{5})$" },
  { country: "Mexico", code: "MX", regex: "^\\d{5}$" },
  { country: "Micronesia", code: "FM", regex: "^\\d{5}(-\\d{4})?$" },
  { country: "Moldova", code: "MD", regex: "^MD-?\\d{4}$" },
  { country: "Monaco", code: "MC", regex: "^980\\d{2}$" },
  { country: "Mongolia", code: "MN", regex: "^\\d{5}$" },
  { country: "Montenegro", code: "ME", regex: "^\\d{5}$" },
  { country: "Morocco", code: "MA", regex: "^\\d{5}$" },
  { country: "Mozambique", code: "MZ", regex: "^\\d{4}$" },
  { country: "Myanmar", code: "MM", regex: "^\\d{5}$" },
  { country: "Namibia", code: "NA", regex: null },
  { country: "Nauru", code: "NR", regex: null },
  { country: "Nepal", code: "NP", regex: "^\\d{5}$" },
  { country: "Netherlands", code: "NL", regex: "^[1-9]\\d{3} ?[A-Z]{2}$" },
  { country: "New Zealand", code: "NZ", regex: "^\\d{4}$" },
  { country: "Nicaragua", code: "NI", regex: "^\\d{5}$" },
  { country: "Niger", code: "NE", regex: "^\\d{4}$" },
  { country: "Nigeria", code: "NG", regex: "^\\d{6}$" },
  { country: "North Korea", code: "KP", regex: null },
  { country: "North Macedonia", code: "MK", regex: "^\\d{4}$" },
  { country: "Norway", code: "NO", regex: "^\\d{4}$" },
  { country: "Oman", code: "OM", regex: "^\\d{3}$" },
  { country: "Pakistan", code: "PK", regex: "^\\d{5}$" },
  { country: "Palau", code: "PW", regex: "^96940$" },
  { country: "Palestine", code: "PS", regex: "^\\d{3}$" },
  { country: "Panama", code: "PA", regex: "^\\d{4}$" },
  { country: "Papua New Guinea", code: "PG", regex: "^\\d{3}$" },
  { country: "Paraguay", code: "PY", regex: "^\\d{4}$" },
  { country: "Peru", code: "PE", regex: "^\\d{5}$" },
  { country: "Philippines", code: "PH", regex: "^\\d{4}$" },
  { country: "Poland", code: "PL", regex: "^\\d{2}-\\d{3}$" },
  { country: "Portugal", code: "PT", regex: "^\\d{4}-\\d{3}$" },
  { country: "Qatar", code: "QA", regex: null },
  { country: "Romania", code: "RO", regex: "^\\d{6}$" },
  { country: "Russia", code: "RU", regex: "^\\d{6}$" },
  { country: "Rwanda", code: "RW", regex: null },
  { country: "Saint Kitts and Nevis", code: "KN", regex: null },
  { country: "Saint Lucia", code: "LC", regex: null },
  { country: "Saint Vincent and the Grenadines", code: "VC", regex: "^VC\\d{4}$" },
  { country: "Samoa", code: "WS", regex: null },
  { country: "San Marino", code: "SM", regex: "^4789\\d$" },
  { country: "Sao Tome and Principe", code: "ST", regex: null },
  { country: "Saudi Arabia", code: "SA", regex: "^\\d{5}(-\\d{4})?$" },
  { country: "Senegal", code: "SN", regex: "^\\d{5}$" },
  { country: "Serbia", code: "RS", regex: "^\\d{5}$" },
  { country: "Seychelles", code: "SC", regex: null },
  { country: "Sierra Leone", code: "SL", regex: null },
  { country: "Singapore", code: "SG", regex: "^\\d{6}$" },
  { country: "Slovakia", code: "SK", regex: "^\\d{3} ?\\d{2}$" },
  { country: "Slovenia", code: "SI", regex: "^SI-?\\d{4}$" },
  { country: "Solomon Islands", code: "SB", regex: null },
  { country: "Somalia", code: "SO", regex: "^[A-Z]{2} ?\\d{5}$" },
  { country: "South Africa", code: "ZA", regex: "^\\d{4}$" },
  { country: "South Korea", code: "KR", regex: "^\\d{5}$" },
  { country: "South Sudan", code: "SS", regex: null },
  { country: "Spain", code: "ES", regex: "^\\d{5}$" },
  { country: "Sri Lanka", code: "LK", regex: "^\\d{5}$" },
  { country: "Sudan", code: "SD", regex: "^\\d{5}$" },
  { country: "Suriname", code: "SR", regex: null },
  { country: "Sweden", code: "SE", regex: "^\\d{3} ?\\d{2}$" },
  { country: "Switzerland", code: "CH", regex: "^\\d{4}$" },
  { country: "Syria", code: "SY", regex: null },
  { country: "Tajikistan", code: "TJ", regex: "^\\d{6}$" },
  { country: "Tanzania", code: "TZ", regex: "^\\d{5}$" },
  { country: "Thailand", code: "TH", regex: "^\\d{5}$" },
  { country: "Timor-Leste", code: "TL", regex: null },
  { country: "Togo", code: "TG", regex: null },
  { country: "Tonga", code: "TO", regex: null },
  { country: "Trinidad and Tobago", code: "TT", regex: null },
  { country: "Tunisia", code: "TN", regex: "^\\d{4}$" },
  { country: "Turkey", code: "TR", regex: "^\\d{5}$" },
  { country: "Turkmenistan", code: "TM", regex: "^\\d{6}$" },
  { country: "Tuvalu", code: "TV", regex: null },
  { country: "Uganda", code: "UG", regex: null },
  { country: "Ukraine", code: "UA", regex: "^\\d{5}$" },
  { country: "United Arab Emirates", code: "AE", regex: null },
  { country: "United Kingdom", code: "GB", regex: "^[A-Z]{1,2}\\d[A-Z\\d]? ?\\d[A-Z]{2}$" },
  { country: "United States", code: "US", regex: "^\\d{5}(-\\d{4})?$" },
  { country: "Uruguay", code: "UY", regex: "^\\d{5}$" },
  { country: "Uzbekistan", code: "UZ", regex: "^\\d{6}$" },
  { country: "Vanuatu", code: "VU", regex: null },
  { country: "Vatican City", code: "VA", regex: "^00120$" },
  { country: "Venezuela", code: "VE", regex: "^\\d{4}$" },
  { country: "Vietnam", code: "VN", regex: "^\\d{5}$" },
  { country: "Yemen", code: "YE", regex: null },
  { country: "Zambia", code: "ZM", regex: "^\\d{5}$" },
  { country: "Zimbabwe", code: "ZW", regex: null }
];



function createOptions() {
    const select = document.querySelector("#countries")
    for(let i = 0; i < countries.length; i++) {
        const option = document.createElement("option")
        option.value = countries[i].code
        option.textContent = countries[i].country
        select.append(option)
    }
}

createOptions()
